package model;

public class AuthData {
    private String authToken; // Auth token generated by the server for each user
    private String username; // Username of the user

    // Constructor for AuthData
    public AuthData(String authToken, String username) {
        this.authToken = authToken;
        this.username = username;
    }

    // Getters to get stuff to be got
    public String getAuthToken() {
        //System.out.println("Auth Token: " + authToken);
        return authToken;
    }
    public String getUsername() {
        //System.out.println("Username: " + username);
        return username;
    }
}